module.exports = {
  meme: [
    { label: "Fart", file: "fartmeme.mp3" },
    { label: "Bad to the Bone", file: "bad-to-the-bone-meme.mp3" },
    { label: "A Few Moments Later", file: "a-few-moments-later.mp3" },
    { label: "Disgostang", file: "disgusting.mp3" },
    { label: "Do the Roar", file: "do-the-roar-11.mp3" },
    { label: "Shrek Swamp", file: "what-are-you-doing-in-my-swamp-.mp3" },
    { label: "Drake Embarrassing", file: "drake-embarrassing.mp3" },
    { label: "Klonk", file: "klonk.mp3" },
    { label: "Im Pickle Rick", file: "pickle_rick.mp3" },
    { label: "Vine Boom", file: "vine-boom.mp3" },
    { label: "Windows Startup", file: "windows-xp-startup.mp3" },
  ],
  angry: [
    { label: "This Guy Stinks", file: "this-guy-stink.mp3" },
    { label: "I Dont Give a Shit", file: "gilbertgottfried.mp3" },
    { label: "wtf", file: "alan-smiling-friends-what-the-fuck.mp3" },
    { label: "Avada Kedavra", file: "avada-kedavra.mp3" },
    { label: "Nooo", file: "nooo.mp3" },
    { label: "Punch", file: "punch-gaming-sound-effect.mp3" },
    { label: "Spongebob Fail", file: "spongebob-fail.mp3" },
    { label: "Steve OOH", file: "steve-old-hurt-sound.mp3" },
    { label: "Sad Music", file: "tf_nemesis.mp3" },
    { label: "Who Cares", file: "who-the-hell-cares-family-guy-peter.mp3" },
  ],
  happy: [
    { label: "Yay", file: "children-yay.mp3" },
    { label: "Ding", file: "ding.mp3" },
    { label: "W's in the Chat", file: "ws-in-de-chat.mp3" },
    { label: "Aha", file: "family-guy-ostrich-laugh.mp3" },
    { label: "Good Morning Pineapple", file: "good-morning-pineapple.mp3" },
    { label: "Jeremy Noise", file: "jeremy-noise.mp3" },
    { label: "Lets a Go", file: "lets-a-go-mario-23.mp3" },
    { label: "Celebration", file: "celebration.mp3" },
  ],
};
